import 'package:flutter/material.dart';
import '../services/admin_service.dart';

class AdvisorsAdminScreen extends StatefulWidget{const AdvisorsAdminScreen({super.key});@override State<AdvisorsAdminScreen> createState()=>_State();}
class _State extends State<AdvisorsAdminScreen>{
  late Future<List<Map<String,dynamic>>> future; @override void initState(){super.initState();future=AdminService.advisors();} void reload()=>setState(()=>future=AdminService.advisors());
  Future<void> edit(Map<String,dynamic> a)async{String role=a['role']?.toString()??'asesor';bool active=a['active']!=false;final ok=await showDialog<bool>(context:context,builder:(_)=>StatefulBuilder(builder:(context,setLocal)=>AlertDialog(title:Text(a['full_name']??'Usuario'),content:SizedBox(width:430,child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:role,items:const [DropdownMenuItem(value:'asesor',child:Text('Asesor')),DropdownMenuItem(value:'capacitador',child:Text('Capacitador')),DropdownMenuItem(value:'team_leader',child:Text('Team Leader')),DropdownMenuItem(value:'admin',child:Text('Administrador'))],onChanged:(v){if(v!=null)setLocal(()=>role=v);},decoration:const InputDecoration(labelText:'Rol')),SwitchListTile(value:active,onChanged:(v)=>setLocal(()=>active=v),title:const Text('Usuario activo'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Guardar'))])));if(ok==true){await AdminService.updateProfileRole(a['id'].toString(),role);await AdminService.setProfileActive(a['id'].toString(),active);reload();}}
  @override Widget build(BuildContext context)=>SafeArea(child:FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(padding:const EdgeInsets.all(30),children:[const Text('Usuarios y roles',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const Text('Administra asesores, capacitadores, Team Leaders y administradores.'),const SizedBox(height:18),...s.data!.map((a)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(a['full_name']??'',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${a['email']??''} · ${a['area']??'Sin área'}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Chip(label:Text(a['role']??'')),IconButton(icon:const Icon(Icons.edit),onPressed:()=>edit(a))]))))]);}));
}
