import 'package:flutter/material.dart';
import '../services/admin_service.dart';

class AssignmentsAdminScreen extends StatefulWidget{const AssignmentsAdminScreen({super.key});@override State<AssignmentsAdminScreen> createState()=>_State();}
class _State extends State<AssignmentsAdminScreen>{late Future<List<Map<String,dynamic>>> future;@override void initState(){super.initState();future=AdminService.assignments();}void reload()=>setState(()=>future=AdminService.assignments());
Future<void> create()async{final courses=await AdminService.courses();final users=(await AdminService.advisors()).where((u)=>u['role']=='asesor').toList();if(!mounted||courses.isEmpty||users.isEmpty)return;int courseId=(courses.first['id']as num).toInt();String userId=users.first['id'].toString();DateTime? due;
final ok=await showDialog<bool>(context:context,builder:(_)=>StatefulBuilder(builder:(context,setLocal)=>AlertDialog(title:const Text('Asignar curso'),content:SizedBox(width:560,child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<int>(initialValue:courseId,items:courses.map((c)=>DropdownMenuItem(value:(c['id']as num).toInt(),child:Text(c['title']??''))).toList(),onChanged:(v){if(v!=null)setLocal(()=>courseId=v);},decoration:const InputDecoration(labelText:'Curso')),const SizedBox(height:10),DropdownButtonFormField<String>(initialValue:userId,items:users.map((u)=>DropdownMenuItem(value:u['id'].toString(),child:Text(u['full_name']??''))).toList(),onChanged:(v){if(v!=null)setLocal(()=>userId=v);},decoration:const InputDecoration(labelText:'Asesor')),const SizedBox(height:10),ListTile(title:Text(due==null?'Sin fecha límite':'Fecha: ${due!.year}-${due!.month.toString().padLeft(2,'0')}-${due!.day.toString().padLeft(2,'0')}'),trailing:const Icon(Icons.calendar_month),onTap:()async{final picked=await showDatePicker(context:context,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:365)));if(picked!=null)setLocal(()=>due=picked);})])),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Asignar'))])));
if(ok==true){await AdminService.saveAssignment(courseId,userId,due);reload();}}
@override Widget build(BuildContext context)=>SafeArea(child:FutureBuilder<List<Map<String,dynamic>>>(future:future,builder:(context,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(padding:const EdgeInsets.all(30),children:[Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Plan de capacitación',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),Text('Asigna cursos a asesores y define fechas objetivo.') ])),FilledButton.icon(onPressed:create,icon:const Icon(Icons.add_task),label:const Text('Asignar curso'))]),const SizedBox(height:18),...s.data!.map((r)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.assignment_turned_in_outlined)),title:Text(r['courses']?['title']??'',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${r['profiles']?['full_name']??''} · vence ${r['due_at']??'sin fecha'}'))))]);}));}
